### ISSUE TITLE
Progress on Zip Bomb vulnerability

### ISSUE THREAD

**Issue by krnick** [vstinner/python-security#20]
Hello @vstinner ,

Thank you very much for recording all the issues related to Python security.
I am Junwei Song, the reporter of the zip bomb vulnerability.

This patch does not fix the CPython zipfile library itself. Instead, we improved the documentation with Serhiy and Christian's suggestion to inform users of the problems they might have and the pull request got merged last week.

The link below is the pull request
https://github.com/python/cpython/pull/13378

Also, the improvement of the documentation was 
committed in versions 3.8 and 3.9 😄.

Thank you!

**Comment by vstinner** [comment]
I removed Zip Bomb from vulnerabilities and document it instead:
https://github.com/vstinner/python-security/commit/33037c86f7a8e2c69de143882849e6d275df2881
