### ISSUE TITLE
Thoughts on elevating content to more visible location

### ISSUE THREAD

**Issue by sethmlarson** [vstinner/python-security#41]
Thanks for maintaining this resource! There's a lot of quality information here. For two separate reasons I wanted to reach out to see if you had interest in elevating a bunch of the content in this project into more visible places.

From my reading, a lot of the information under the "Python Security" section would make sense in the CPython devguide, especially the security model (which I'd like to invest more time in developing too!) I haven't sought out consensus among core devs to do this, but wanted to check with you first to see if you're interested in seeing this type of migration occur?

Secondly, as a part of my work to make process improvements to the PSRT I'm working on getting the PSF designated as a CNA and one of the requirements is having a place where advisories are published publicly. I'd like to make the advisories available in a machine readable format like OSV similar to what you've done here, so to me it also makes sense to import the historical advisories into the same list.

Let me know your thoughts, and thanks again.

**Comment by sethmlarson** [comment]
Part two of this issue has a PR here: https://github.com/vstinner/python-security/pull/42

**Comment by vstinner** [comment]
> From my reading, a lot of the information under the "Python Security" section would make sense in the CPython devguide, especially the security model (which I'd like to invest more time in developing too!) I haven't sought out consensus among core devs to do this, but wanted to check with you first to see if you're interested in seeing this type of migration occur?

devguide is very opinionated, it's hard to get any change merged, people like nitpicking. I felt that it was easier to have my own space for my docs related to security.

If someone else wants to contribute to the devguide, so, go head :-) You can copy my docs there if you. If tomorrow, most content is moved to better places, maybe I can just close this space.

I merged your PR, thanks.
